ARJ.Pianopoli.Admin.6/Controllers/PropostasController.cs
using ARJ.Pianopoli.Admin._6.Core;
using ARJ.Pianopoli.Admin._6.Data;
using ARJ.Pianopoli.Admin._6.Models;
using ARJ.Pianopoli.Admin._6.Utils;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Globalization;
using System.Net;
using System.Security.Claims;
using System.Text;
using Document = iTextSharp.text.Document;
using Font = iTextSharp.text.Font;
using PageSize = iTextSharp.text.PageSize;
using Paragraph = iTextSharp.text.Paragraph;


namespace ARJ.Pianopoli.Admin._6.Controllers
{
    public class PropostasController : Controller
    {
        private readonly DBContext db;
        static BaseFont fontebase = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1252, false);
        private IWebHostEnvironment _hostingEnvironment;
        private readonly IAspNetUser _user;
        private readonly Microsoft.AspNetCore.Identity.UserManager<IdentityUser> _userManager;

        public PropostasController(DBContext db, IWebHostEnvironment hostingEnvironment, IAspNetUser user, Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager )
        {
            this.db = db;
            _hostingEnvironment = hostingEnvironment;
            _user = user;
            _userManager = userManager;
        }

        // public IActionResult ControlePainel() => Content("Controle Painel");



        [Authorize]
        public IActionResult Index()
        {
            //var user = await _userManager.GetUserAsync(User);
            //var roles = await _userManager.GetRolesAsync(user);
            

            ViewBag.Corretor = (from f in db.Corretores
                                where f.DataExclusao == null
                                select new SelectListItem
                                {
                                    Text = f.Nome,
                                    Value = f.Id.ToString()
                                });

            ViewBag.Loteamento = (from f in db.Loteamentos
                                  select new SelectListItem
                                  {
                                      Text = f.Nome,
                                      Value = f.Id.ToString()
                                  });

            ViewBag.EstadoCivil = (from f in db.EstadoCivil
                                   select new SelectListItem
                                   {
                                       Text = f.Descricao,
                                       Value = f.Id.ToString()
                                   });
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToPage("/");
            }
        }
        public IActionResult CondicoesComerciaisId(int Id)
        {
            var lote = db.Lotes.Where(c => c.Id == Id).FirstOrDefault();
            if (lote == null)
            {
                return RedirectToAction("CondicoesComerciais", new { Loteamentoid = lote.LoteamentoId, Quadra = lote.Quadra, Lote = lote.Lote, Tipo = 2 });

            }
            else
            {
                return RedirectToAction("CondicoesComerciais", new { Loteamento = lote.LoteamentoId, Quadra = lote.Quadra, Lote = lote.Lote, Tipo = 2 });
            }
        }
        public IActionResult GerarPdfCondicoesComerciais(int? Id)
        {
            if (ModelState.IsValid)
            {
                var usuario = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var nome = _user.Name;

                var modelo = new CondicoesViewModel();
                var lote = db.Lotes.Where(c => c.Id == Id).FirstOrDefault();
                // monta dados do lote 
                modelo.Registro = lote.Id;
                modelo.Lote = lote.Lote;
                modelo.Quadra = lote.Quadra;
                modelo.Area = lote.Area;
                modelo.LoteamentoId = lote.LoteamentoId;
                modelo.PrecoM2 = db.TabelaM2.Where(c => c.CategoriaId == lote.CategoriaId).FirstOrDefault().ValorM2;
                if (lote.SituacaoNoSite == "1")
                {
                    // busca o valor total do lote quando este ainda está disponível e sem proposta enviada.
                    var precoVenda = Math.Round(modelo.PrecoM2 * lote.Area, 2); //db.TabelaPrecoLotes.Where(c => c.Quadra == Quadra && c.Lote == Lote).FirstOrDefault().PrecoVenda;


                    modelo.ValorTotal = (precoVenda);

                    double vlrParcSemestral = 7500.00;   // deverár ser parametrizado
                    double jurosAM = 0.0025;
                    double constante = 1;
                    var entradaPadrao = Math.Round(precoVenda * 0.15m, 2);
                    var saldoPadrao = precoVenda - entradaPadrao;


                    var VP6 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 6)), 2);
                    var VP12 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 12)), 2);
                    var VP18 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 18)), 2);
                    var VP24 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 24)), 2);
                    var VP30 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 30)), 2);
                    var VP36 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 36)), 2);
                    var VP42 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 42)), 2);
                    var VP48 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 48)), 2);
                    var VP54 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 54)), 2);
                    var VP60 = Math.Round((vlrParcSemestral / Math.Pow((constante + jurosAM), 60)), 2);

                    var parc12 = 7000.00m;
                    var parc24 = Math.Round(((((double)(saldoPadrao * 0.60m)) - (VP6 + VP12 + VP18 + VP24)) * (((jurosAM * (Math.Pow(1 + jurosAM, 24))) / Math.Pow(1 + jurosAM, 24)) - 1)) / -24, 2);
                    var parc36 = Math.Round(((((double)(saldoPadrao * 0.60m)) - (VP6 + VP12 + VP18 + VP24 + VP30 + VP36)) * (((jurosAM * (Math.Pow(1 + jurosAM, 36))) / Math.Pow(1 + jurosAM, 36)) - 1)) / -36, 2);
                    var parc48 = Math.Round(((((double)(saldoPadrao * 0.60m)) - (VP6 + VP12 + VP18 + VP24 + VP30 + VP36 + VP42 + VP48)) * (((jurosAM * (Math.Pow(1 + jurosAM, 48))) / Math.Pow(1 + jurosAM, 48)) - 1)) / -48, 2);
                    var parc60 = Math.Round(((((double)(saldoPadrao * 0.60m)) - (VP6 + VP12 + VP18 + VP24 + VP30 + VP36 + VP42 + VP48 + VP54 + VP60)) * (((jurosAM * (Math.Pow(1 + jurosAM, 60))) / Math.Pow(1 + jurosAM, 60)) - 1)) / -60, 2);

                    var juros = 0.0025;

                    var listaTabela = new List<CondicoesPlanosViewModel>();
                    listaTabela.Add(new CondicoesPlanosViewModel
                    {
                        Plano = 1,
                        PrecoVenda = precoVenda,
                        Entrada = Math.Round(precoVenda * 0.15m, 2),
                        Saldo = precoVenda - Math.Round(precoVenda * 0.15m, 2),
                        NrParcMen = 12,
                        Mensais = parc12,
                        NrParcSem = 2,
                        Semestrais = (decimal)vlrParcSemestral,
                        TotalPagas = (parc12 * 12) + (2 * (decimal)vlrParcSemestral),
                        SaldoRem = (precoVenda - Math.Round(precoVenda * 0.15m, 2)) - ((parc12 * 12) + (2 * (decimal)vlrParcSemestral)),
                        PrecoComJuros = ((parc12 * 12) + (2 * (decimal)vlrParcSemestral)) + ((precoVenda - Math.Round(precoVenda * 0.15m, 2)) - ((parc12 * 12) + (2 * (decimal)vlrParcSemestral))) + Math.Round(precoVenda * 0.15m, 2),
                        JurosCobrados = (((parc12 * 12) + (2 * (decimal)vlrParcSemestral)) + ((precoVenda - Math.Round(precoVenda * 0.15m, 2)) - ((parc12 * 12) + (2 * (decimal)vlrParcSemestral))) + Math.Round(precoVenda * 0.15m, 2)) - precoVenda
                    });
                    var SaldoRem24 = Math.Round(((precoVenda - Math.Round(precoVenda * 0.15m, 2)) * (decimal)0.4) * (decimal)Math.Pow(1 + juros, 24), 2);
                    var ParcPagas24 = ((decimal)parc24 * 24) + (4 * (decimal)vlrParcSemestral);

                    listaTabela.Add(new CondicoesPlanosViewModel
                    {
                        Plano = 2,
                        PrecoVenda = precoVenda,
                        Entrada = Math.Round(precoVenda * 0.15m, 2),
                        Saldo = precoVenda - Math.Round(precoVenda * 0.15m, 2),
                        NrParcMen = 24,
                        Mensais = (decimal)parc24,
                        NrParcSem = 4,
                        Semestrais = (decimal)vlrParcSemestral,
                        TotalPagas = ((decimal)parc24 * 24) + (4 * (decimal)vlrParcSemestral),
                        SaldoRem = Math.Round(((precoVenda - Math.Round(precoVenda * 0.15m, 2)) * (decimal)0.4) * (decimal)Math.Pow(1 + juros, 24), 2),
                        PrecoComJuros = Math.Round(Math.Round(precoVenda * 0.15m, 2) + (decimal)ParcPagas24 + (decimal)SaldoRem24, 2), // ParcPagas24 + ((precoVenda - Math.Round(precoVenda * 0.15m, 2)) - (((decimal)parc24 * 24) + (4 * (decimal)vlrParcSemestral))) + Math.Round(precoVenda * 0.15m, 2),
                        JurosCobrados = Math.Round(Math.Round(precoVenda * 0.15m, 2) + (decimal)ParcPagas24 + (decimal)SaldoRem24, 2) - precoVenda // (ParcPagas24 + ((precoVenda - Math.Round(precoVenda * 0.15m, 2)) - (((decimal)parc24 * 24) + (4 * (decimal)vlrParcSemestral))) + Math.Round(precoVenda * 0.15m, 2)) - precoVenda
                    });

ARJ.Pianopoli.Admin.6/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ARJ.Pianopoli.Admin._6.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ARJ.Pianopoli.Admin.6/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ARJ.Pianopoli.Admin._6.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ARJ.Pianopoli.Admin.6/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ARJ.Pianopoli.Admin._6.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ARJ.Pianopoli.Admin.6/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pianopoli - Admin</title>

    <link href="css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" asp-append-version="true">
    <script src="https://kit.fontawesome.com/c82fa94686.js" crossorigin="anonymous"></script>

    <!-- Toastr style -->
    <link href="css/plugins/toastr/toastr.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet" asp-append-version="true">
    <link href="css/style.css" rel="stylesheet" asp-append-version="true">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.13.1/themes/flick/jquery-ui.css" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" rel="stylesheet" />


</head>
<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a href="/"> <img alt="image" src="~/images/logo.jpg" width="130" /></a>
                        </div>
                        <div class="logo-element">
                            ARJ+
                        </div>
                    </li>
                    @if(User.Identity.IsAuthenticated)
                    {
                        <li class="active">
                            <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Propostas</span><span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse">
                                <li><a href="~/Propostas">Lista de Propostas</a></li>
                                <li><a href="~/Mapa">Mapa dos lotes</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Tabelas</span><span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse">
                                <li><a href="#">Imobiliárias</a></li>
                                <li><a href="#">Corretores</a></li>
                            </ul>

                        </li>
                        <li>
                            <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Preços</span><span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse">
                                <li><a href="#">Tabela de preços</a></li>
                                <li><a asp-area="" asp-controller="Propostas" asp-action="Index">Listar Propostas</a></li>
                            </ul>
                        </li>
                    }
                </ul>

            </div>
        </nav>
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                    @*<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>*@
                    </div>
                    
                    <ul class="nav navbar-top-links navbar-right">
                        <partial name="_LoginPartial" />
                    </ul>

                </nav>
            </div>
            <div class="wrapper wrapper-content animated fadeInRight">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center m-t-lg">
                            <h1>
                                Propostas - Pianopoli
                            </h1>
                            <small>
                                @if(!User.Identity.IsAuthenticated)
                                {
                                    <p>Use seu usuário e senha para acessar o painel ou entre em contato com o administrador.</p>
                                }
                            </small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer">
                <div class="pull-right">
                </div>
                <div>
                    <strong>Copyright</strong> ARJ Empreendimentos &copy; 2022
                </div>
            </div>
        </div>
    </div>


    <!-- Mainly scripts -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/js/inspinia.js"></script>
    <script src="~/js/plugins/pace/pace.min.js"></script>


    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script type="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="~/js/jquery.imagemapster.min.js" asp-append-version="true"></script>


    <script src="https://unpkg.com/sweetalert2@7.0.6/dist/sweetalert2.all.js"></script>
    <script src="~/js/jquery.blockui.min.js"></script>
    @*<script src="https://releases.jquery.com/git/jquery-migrate-git.min.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.4.0/jquery-migrate.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.7.8/dist/index.bundle.min.js"></script>

    <script type="text/javascript" src="https://cdn.rawgit.com/plentz/jquery-maskmoney/master/dist/jquery.maskMoney.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>